spring:
  application:
    name: booking-service
  profiles:
    active: booking_service
  config:
    import: 'configserver:http://localhost:8888/'
  cloud:
    config:
      name: booking-service,config-client
      username: spring_cloud_user
      password: cloud!