version: '3.7'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=keycloak"
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
      - "PGADMIN_LISTEN_PORT=9092"
    ports:
      - "9092:9092"
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-keycloak}

  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "9091:8080"
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_LOG_LEVEL=INFO"
      - "KC_DB=postgres"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=admin"
      - "KC_DB_URL=jdbc:postgresql://postgres/keycloak?currentSchema=keycloak"
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-keycloak}

volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local