server:
  port: 8383

spring:
  application:
    name: user-service
  profiles:
    active: user_service
  config:
    import: 'configserver:http://localhost:8181'
  cloud:
    config:
      name: user-service,config-client
      username: spring_cloud_user
      password: c1oud!_2020
  security:
    user:
      name: test
      password: test