/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vaccinetracker.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BookingAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7684326933668547595L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookingAvroModel\",\"namespace\":\"com.vaccinetracker.kafka.avro.model\",\"fields\":[{\"name\":\"vaccineCenterId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"vaccineType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookingAvroModel> ENCODER =
      new BinaryMessageEncoder<BookingAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookingAvroModel> DECODER =
      new BinaryMessageDecoder<BookingAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookingAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookingAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookingAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BookingAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookingAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookingAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookingAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookingAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String vaccineCenterId;
  private java.lang.String vaccineType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookingAvroModel() {}

  /**
   * All-args constructor.
   * @param vaccineCenterId The new value for vaccineCenterId
   * @param vaccineType The new value for vaccineType
   */
  public BookingAvroModel(java.lang.String vaccineCenterId, java.lang.String vaccineType) {
    this.vaccineCenterId = vaccineCenterId;
    this.vaccineType = vaccineType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return vaccineCenterId;
    case 1: return vaccineType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: vaccineCenterId = value$ != null ? value$.toString() : null; break;
    case 1: vaccineType = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'vaccineCenterId' field.
   * @return The value of the 'vaccineCenterId' field.
   */
  public java.lang.String getVaccineCenterId() {
    return vaccineCenterId;
  }


  /**
   * Sets the value of the 'vaccineCenterId' field.
   * @param value the value to set.
   */
  public void setVaccineCenterId(java.lang.String value) {
    this.vaccineCenterId = value;
  }

  /**
   * Gets the value of the 'vaccineType' field.
   * @return The value of the 'vaccineType' field.
   */
  public java.lang.String getVaccineType() {
    return vaccineType;
  }


  /**
   * Sets the value of the 'vaccineType' field.
   * @param value the value to set.
   */
  public void setVaccineType(java.lang.String value) {
    this.vaccineType = value;
  }

  /**
   * Creates a new BookingAvroModel RecordBuilder.
   * @return A new BookingAvroModel RecordBuilder
   */
  public static com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder newBuilder() {
    return new com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder();
  }

  /**
   * Creates a new BookingAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookingAvroModel RecordBuilder
   */
  public static com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder newBuilder(com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder other) {
    if (other == null) {
      return new com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder();
    } else {
      return new com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new BookingAvroModel RecordBuilder by copying an existing BookingAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new BookingAvroModel RecordBuilder
   */
  public static com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder newBuilder(com.vaccinetracker.kafka.avro.model.BookingAvroModel other) {
    if (other == null) {
      return new com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder();
    } else {
      return new com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for BookingAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookingAvroModel>
    implements org.apache.avro.data.RecordBuilder<BookingAvroModel> {

    private java.lang.String vaccineCenterId;
    private java.lang.String vaccineType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.vaccineCenterId)) {
        this.vaccineCenterId = data().deepCopy(fields()[0].schema(), other.vaccineCenterId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.vaccineType)) {
        this.vaccineType = data().deepCopy(fields()[1].schema(), other.vaccineType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing BookingAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vaccinetracker.kafka.avro.model.BookingAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.vaccineCenterId)) {
        this.vaccineCenterId = data().deepCopy(fields()[0].schema(), other.vaccineCenterId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vaccineType)) {
        this.vaccineType = data().deepCopy(fields()[1].schema(), other.vaccineType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'vaccineCenterId' field.
      * @return The value.
      */
    public java.lang.String getVaccineCenterId() {
      return vaccineCenterId;
    }


    /**
      * Sets the value of the 'vaccineCenterId' field.
      * @param value The value of 'vaccineCenterId'.
      * @return This builder.
      */
    public com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder setVaccineCenterId(java.lang.String value) {
      validate(fields()[0], value);
      this.vaccineCenterId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'vaccineCenterId' field has been set.
      * @return True if the 'vaccineCenterId' field has been set, false otherwise.
      */
    public boolean hasVaccineCenterId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'vaccineCenterId' field.
      * @return This builder.
      */
    public com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder clearVaccineCenterId() {
      vaccineCenterId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'vaccineType' field.
      * @return The value.
      */
    public java.lang.String getVaccineType() {
      return vaccineType;
    }


    /**
      * Sets the value of the 'vaccineType' field.
      * @param value The value of 'vaccineType'.
      * @return This builder.
      */
    public com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder setVaccineType(java.lang.String value) {
      validate(fields()[1], value);
      this.vaccineType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'vaccineType' field has been set.
      * @return True if the 'vaccineType' field has been set, false otherwise.
      */
    public boolean hasVaccineType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'vaccineType' field.
      * @return This builder.
      */
    public com.vaccinetracker.kafka.avro.model.BookingAvroModel.Builder clearVaccineType() {
      vaccineType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookingAvroModel build() {
      try {
        BookingAvroModel record = new BookingAvroModel();
        record.vaccineCenterId = fieldSetFlags()[0] ? this.vaccineCenterId : (java.lang.String) defaultValue(fields()[0]);
        record.vaccineType = fieldSetFlags()[1] ? this.vaccineType : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookingAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookingAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookingAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<BookingAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.vaccineCenterId);

    out.writeString(this.vaccineType);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.vaccineCenterId = in.readString();

      this.vaccineType = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.vaccineCenterId = in.readString();
          break;

        case 1:
          this.vaccineType = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










