server:
  port: 8181

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: INFO

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/michal-sokolnicki/spring-cloud-config-repository.git
          username: michal-sokolnicki
          password: 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
          default-label: main
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: c1oud!_2020